import ReactMarkdown from 'react-markdown';

interface ProposalTabProps {
    data: any;
}

export default function ProposalTab({ data }: ProposalTabProps) {
    const content = data.proposal?.content || '';

    return (
        <div className="max-w-4xl mx-auto bg-surface p-8 rounded-lg shadow-2xl min-h-[600px] border border-gray-800">
            <header className="flex justify-between items-center mb-8 pb-6 border-b border-gray-700">
                <div>
                    <h2 className="text-2xl font-bold font-serif text-white">Supply Proposal Draft</h2>
                    <p className="text-gray-400 text-sm">Generated by FMCG Agent • Kitchen Appliances Division</p>
                </div>
                <button
                    onClick={() => navigator.clipboard.writeText(content)}
                    className="px-4 py-2 border border-blue-500/30 text-blue-400 hover:bg-blue-500/10 rounded-md text-sm transition-colors"
                >
                    Copy to Clipboard
                </button>
            </header>

            <article className="prose prose-invert prose-headings:text-blue-300 prose-p:text-gray-300 prose-a:text-primary max-w-none">
                {content ? <ReactMarkdown>{content}</ReactMarkdown> : <p className="text-gray-500 italic">No proposal generated yet.</p>}
            </article>
        </div>
    );
}
